sudo: required
dist: trusty
language: python
python:
  - '2.7'
install:
  - pip install -r ci/requirements.txt
  - git clone https://github.com/QubesOS/qubes-builder ~/qubes-builder
# debootstrap in trusty is old...
before_script: sudo ln -s sid /usr/share/debootstrap/scripts/stretch
script:
  - PYTHONPATH=test-packages pylint --rcfile=ci/pylintrc qubes
  - ./run-tests --no-syslog
  - ~/qubes-builder/scripts/travis-build
env:
 - DIST_DOM0=fc23 USE_QUBES_REPO_VERSION=3.2 USE_QUBES_REPO_TESTING=1
